version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: festiguide-ruby-sql
    volumes:
      - festiguide-ruby-mysql:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "festiguide_db"
      MYSQL_USER: "database_user"
      MYSQL_PASSWORD: "password"
volumes:
  festiguide-ruby-mysql:
    external: true